services:
  springboot:
    container_name: mzregret
    image: mzregret/develop:latest
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev-env # 사용할 profile
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
